### ISSUE TITLE
Failed to resolve import "@ztstory/datav-core" from "src\pages\index.vue". Does the file exist?

### ISSUE THREAD

**Issue by qew4** [ZTStory/vue-datav#1]
![error4](https://user-images.githubusercontent.com/16102992/202347470-218be4cc-ce22-401a-9490-ebffa15d5229.png)

**Comment by ZTStory** [comment]
你用的是pnpm运行的吗？这个项目用了pnpm workspace管理依赖

**Comment by qew4** [comment]
信我已经收到 谢谢你！
